/// Flutter icons AllTalkIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AllTalkIcons
///      fonts:
///       - asset: fonts/AllTalkIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class AllTalkIcons {
  AllTalkIcons._();

  static const _kFontFam = 'AllTalkIcons';
  static const String? _kFontPkg = null;

  static const IconData sound = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot_3 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_beamed = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popup = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf318, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf32d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
